// Seed data for MVP prototype — will be replaced by Supabase queries
export const SEED_OPPORTUNITIES = [
    {
        id: '1',
        title: 'Urban Tree Planting Day',
        description: 'Help us plant 200 trees in the Eixample district. All tools and training provided. Perfect for first-timers! We\'ll be working alongside the city\'s environmental team to restore native species and boost urban biodiversity.',
        cause_domain: 'Climate Action',
        organizer_name: 'Barcelona Green Alliance',
        organizer_verified: true,
        date_time: '2026-03-08T09:00:00Z',
        duration_minutes: 180,
        location_address: 'Parc de la Ciutadella, Barcelona',
        location_lat: 41.3879,
        location_lng: 2.1699,
        capacity: 30,
        requirements: 'Wear comfortable clothes and sturdy shoes. Gloves provided.',
        image_url: null,
        status: 'active',
        spots_left: 12
    },
    {
        id: '2',
        title: 'Language Café for Refugees',
        description: 'Practice Spanish conversation with newly arrived refugees in a relaxed café setting. No teaching experience needed — just patience and a smile. Coffee and snacks provided by our partner bakery.',
        cause_domain: 'Social Justice',
        organizer_name: 'Benvinguts Initiative',
        organizer_verified: true,
        date_time: '2026-03-05T17:00:00Z',
        duration_minutes: 120,
        location_address: 'Café Cometa, Carrer del Parlament 20, Barcelona',
        location_lat: 41.3762,
        location_lng: 2.1622,
        capacity: 15,
        requirements: 'Conversational Spanish (B1+). Friendly attitude!',
        image_url: null,
        status: 'active',
        spots_left: 6
    },
    {
        id: '3',
        title: 'Kids Coding Workshop (Volunteer Mentor)',
        description: 'Guide a group of 8–12 year-olds through their first Scratch project. You\'ll be paired with 2–3 kids. Curriculum is provided — you just bring enthusiasm and patience.',
        cause_domain: 'Education',
        organizer_name: 'Codi per a Tothom',
        organizer_verified: true,
        date_time: '2026-03-10T14:00:00Z',
        duration_minutes: 150,
        location_address: 'Centre Cívic Pati Llimona, Barcelona',
        location_lat: 41.3825,
        location_lng: 2.1802,
        capacity: 10,
        requirements: 'Basic programming knowledge. DBS check completed (we can help).',
        image_url: null,
        status: 'active',
        spots_left: 4
    },
    {
        id: '4',
        title: 'Food Rescue & Distribution',
        description: 'Collect surplus food from local markets and restaurants, sort it at our hub, and distribute care packages to people sleeping rough. A direct, hands-on way to fight food waste and hunger at the same time.',
        cause_domain: 'Community Building',
        organizer_name: 'FoodShare Barcelona',
        organizer_verified: false,
        date_time: '2026-03-06T07:00:00Z',
        duration_minutes: 240,
        location_address: 'Mercat de Sant Antoni, Barcelona',
        location_lat: 41.3772,
        location_lng: 2.1631,
        capacity: 20,
        requirements: 'Able to carry boxes (up to 10kg). Early start!',
        image_url: null,
        status: 'active',
        spots_left: 8
    },
    {
        id: '5',
        title: 'Animal Shelter Morning Help',
        description: 'Walk dogs, socialize cats, and help clean enclosures at Barcelona\'s largest animal shelter. A great way to spend a Saturday morning if you love animals but can\'t have your own pet.',
        cause_domain: 'Animal Welfare',
        organizer_name: 'Fundació FAADA',
        organizer_verified: true,
        date_time: '2026-03-15T08:30:00Z',
        duration_minutes: 180,
        location_address: 'Centre d\'Acollida d\'Animals, Barcelona',
        location_lat: 41.4207,
        location_lng: 2.1873,
        capacity: 12,
        requirements: 'No allergies to animals. Closed-toe shoes.',
        image_url: null,
        status: 'active',
        spots_left: 5
    },
    {
        id: '6',
        title: 'Beach & River Cleanup',
        description: 'Join us for a 3-hour cleanup along the Barceloneta beach. Bags, grabbers, and gloves provided. We\'ll record and weigh everything we collect for our impact report.',
        cause_domain: 'Climate Action',
        organizer_name: 'Clean Coast Initiative',
        organizer_verified: false,
        date_time: '2026-03-22T10:00:00Z',
        duration_minutes: 180,
        location_address: 'Platja de la Barceloneta, Barcelona',
        location_lat: 41.3760,
        location_lng: 2.1920,
        capacity: 40,
        requirements: 'Dress for weather. Sunscreen recommended.',
        image_url: null,
        status: 'active',
        spots_left: 22
    }
];

// Cause domain colors — warm, earthy tones matching the editorial palette
export const CAUSE_COLORS = {
    'Climate Action': { bg: 'rgba(45, 106, 79, 0.08)', text: '#1B4332' },
    'Social Justice': { bg: 'rgba(120, 53, 114, 0.08)', text: '#78356E' },
    'Education': { bg: 'rgba(30, 64, 146, 0.08)', text: '#1E4092' },
    'Animal Welfare': { bg: 'rgba(184, 134, 11, 0.08)', text: '#8B6914' },
    'Community Building': { bg: 'rgba(194, 84, 10, 0.08)', text: '#C2540A' },
    'Health & Wellbeing': { bg: 'rgba(178, 50, 41, 0.08)', text: '#B23229' },
    'Arts & Culture': { bg: 'rgba(107, 62, 138, 0.08)', text: '#6B3E8A' },
    'Poverty Alleviation': { bg: 'rgba(153, 100, 42, 0.08)', text: '#99642A' },
};
